### PR TITLE
feat(push notification): send calendar push notification to mobile

### PR DESCRIPTION
**Pull request by omobosteven**
#### What does this PR do?
- Ensures that calendar push notifications are received on the backend and passed to the Android application.

#### Description of Task to be completed?
- To receive a push notification on the backend you have to register and verify the application domains `https://converge-api.andela.com` and `https://converge-staging-api.andela.com` on Google console api and ensure that the Google calendar api is enabled on the project.
- An endpoint that creates the notification channels for each room calendar should be created.
- An endpoint [POST] that listens for the notification from the google calendar push notification api should be created (Google sends a post request to `https://[registered domain]/notifications`)
- On successful receiving of the notification. The notification should be passed to the Android app using the `pyfcm [python's firebase cloud messaging]` package.

#### How should this be manually tested?
- Clone the branch
- Run `python manage.py runserver`
- Send a request to the api endpoint `http://127.0.0.1:5000/channels`
This will create notification channels for the rooms on the database using the room's calender_id
- On every event changes on the google calendar a post request would be sent to `https://registered-domain/notifications`

#### What are the relevant pivotal tracker stories?
[#161838908](https://www.pivotaltracker.com/story/show/161838908)

#### Any background context you want to provide?
- You'll need to change/add the following on your .env file
`[API_KEY]`
`[OOATH2_CLIENT_ID]`
`[OOATH2_CLIENT_SECRET]`
`[FCM_API_KEY]`

#### Screenshots
- Showing the successful creation of a notification channel
screen shot 2019-02-12 at 1 15 40 am

- Showing notifications recieved from google calender api on event changes using a mock server [ngrok](https://ngrok.com/download) 
- `success:1` means the notification was successfully sent to the android app
screen shot 2019-01-31 at 11 09 54 am

### CODE REVIEW

**Comment by joshuaocero** [comment]
@omobosteven have you tested this? I believe the GraphQL query fields should be calendar_id and firebase_token. Otherwise this looks good so far

**Comment by joshuaocero** [comment]
Also, I like the mock server view! Shall we be able to see something like that for all notifications coming in? This would help the Android guys do their own debugging first before they reach out to us.

**Comment by omobosteven** [comment]
> @omobosteven have you tested this? I believe the GraphQL query fields should be calendar_id and firebase_token. Otherwise this looks good so far

@joshuaocero, Yes I have tested on my end, I'm waiting for the Android team to verify from their end too.
 Yes the GraphQL query fields are the calendar_id and firebase_token

**Comment by omobosteven** [comment]
> Also, I like the mock server view! Shall we be able to see something like that for all notifications coming in? This would help the Android guys do their own debugging first before they reach out to us.

I don't know if this would be possible when the notifications are sent to the converge domain(https://converge-api.andela.com).
`ngrok` generates a random domain which is mapped to my localhost:5000 development server. I was able to verify the generated domain on google.

generating a custom domain is a paid service (so it might work).

For the Android guys, I would find out if they can see this in the firebase console.

**Comment by omobosteven** [comment]
@joshuaocero, there is a concern I have regarding this task.
If there is a change in the room resource in the database (especially the firebase token) the server needs to be restarted so it can capture these changes. I believe this would be a DevOps task.

**Comment by joshuaocero** [comment]
@omobosteven let's introduce data persistence and implement a new endpoint that the API will call whenever there is a change to the token.

**Comment by omobosteven** [comment]
> @omobosteven let's introduce data persistence and implement a new endpoint that the API will call whenever there is a change to the token.

Alright, noted.

**Comment by omobosteven** [comment]
@joshuaocero, I have implemented the requested changes.

**Comment by joshuaocero** [comment]
@omobosteven looking great! One last change and we should be good. Please decouple this feature from Converge business logic. Let's align more to the calendar API naming convention. Please change `Room` model to `Calendar` and endpoint `save_rooms` to simply `refresh`

**Comment by omobosteven** [comment]
> @omobosteven looking great! One last change and we should be good. Please decouple this feature from Converge business logic. Let's align more to the calendar API naming convention. Please change `Room` model to `Calendar` and endpoint `save_rooms` to simply `refresh`

Noted.

**Comment by omobosteven** [comment]
@joshuaocero, I have implemented the requested changes.

**Review by joshuaocero — APPROVED** [review]

**Pull request merged**
